// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TastebudsGalore.Data;

namespace TastebudsGalore.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20210304164757_QueryingData")]
    partial class QueryingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TastebudsGalore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TastebudsGalore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tomato sauce, mozarella, basil.",
                            ItemId = 1,
                            Name = "Margharita"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomato sauce, mozarella, ham, mushrooms.",
                            ItemId = 2,
                            Name = "Capriciosa"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tomato sauce, mozarella, spicy salami, red onion.",
                            ItemId = 3,
                            Name = "Diavola"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tomato sauce, mozarella, pineapple, ham.",
                            ItemId = 4,
                            Name = "Hawaiian"
                        });
                });

            modelBuilder.Entity("TastebudsGalore.Models.Category", b =>
                {
                    b.HasOne("TastebudsGalore.Models.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("TastebudsGalore.Models.Product", b =>
                {
                    b.OwnsOne("TastebudsGalore.Models.Item", "Item", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<decimal>("Price")
                                .HasColumnType("Money");

                            b1.HasKey("Id");

                            b1.ToTable("Items");

                            b1.WithOwner("Product")
                                .HasForeignKey("Id");

                            b1.Navigation("Product");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Price = 20.0m
                                },
                                new
                                {
                                    Id = 2,
                                    Price = 22.0m
                                },
                                new
                                {
                                    Id = 3,
                                    Price = 24.0m
                                },
                                new
                                {
                                    Id = 4,
                                    Price = 22.0m
                                });
                        });

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TastebudsGalore.Models.Product", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
